# -*- coding: utf-8 -*-
"""Tracker_(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y21OdMHEdKuRvA9dssmXoyrqnQjHSrfc

# **RUN THE CODE AND IT WILL GET UPDATED**
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from datetime import datetime, timedelta

from google.colab import files
import io


try:
  uploaded
except NameError:
  uploaded = files.upload()

df = pd.read_excel("pythonmaster.xlsx")

df

# Convert Date of Publishing to datetime
df["Date of Publishing"] = pd.to_datetime(df["Date of Publishing"], dayfirst=True)

# Define time periods for 3M and 6M prices
today = datetime.today()
three_months_ago = today - timedelta(days=90)
six_months_ago = today - timedelta(days=180)

results = []

# Iterate through each row in the input DataFrame
for _, row in df.iterrows():
    company = row["Company Name"]
    ticker = str(row["Ticker"]).strip()
    index = row["Index"]  # Capture the Index column
    record_price = row["Record Price"]
    target_price = row["Target Price"]
    pub_date = row["Date of Publishing"]

    print(f"Processing {company} ({ticker}) ...")

    try:
        stock = yf.Ticker(ticker)
        hist = stock.history(period="1y")

        if hist.empty or "Close" not in hist:
            print(f"No data for {ticker}")
            continue

        hist.index = hist.index.tz_localize(None)

        # Current Price
        current_price = hist["Close"].iloc[-1]

        # Nearest available 3M price
        hist_3m = hist[hist.index >= three_months_ago]
        price_3m = hist_3m["Close"].iloc[0] if not hist_3m.empty else None

        # Nearest available 6M price
        hist_6m = hist[hist.index >= six_months_ago]
        price_6m = hist_6m["Close"].iloc[0] if not hist_6m.empty else None

        # Calculate percentage changes
        irr_current = ((current_price - record_price) / record_price) * 100 if current_price else None
        irr_3m = ((price_3m - record_price) / record_price) * 100 if price_3m else None
        irr_6m = ((price_6m - record_price) / record_price) * 100 if price_6m else None

        # Append results, including the Index column
        results.append({
            "Date of Publishing": pub_date.date(),
            "Company Name": company,
            "Ticker": ticker,
            "Index": index,  # Include the Index column
            "Record Price": record_price,
            "Current Price": round(current_price, 2) if current_price else None,
            "target Price": target_price,
            "Price 3M": round(price_3m, 2) if price_3m else None,
            "Price 6M": round(price_6m, 2) if price_6m else None,
            "Absolute Current Price (%)": round(irr_current, 2) if irr_current else None,
            "Absolute 3M Price (%)": round(irr_3m, 2) if irr_3m else None,
            "Absolute 6M Price (%)": round(irr_6m, 2) if irr_6m else None
        })

    except Exception as e:
        print(f"Error with {ticker}: {e}")
        continue

# Create final DataFrame
final_df = pd.DataFrame(results)

# Save to CSV
final_df.to_csv("BSE_Final_Output.csv", index=False)

print("Processing Complete! Results saved to BSE_Final_Output.csv")

final_df = pd.DataFrame(results)
final_df

final_df.describe()

final_df['Absolute Current Price (%)'].min()

from google.colab import files
files.download("BSE_Final_Output.csv")



final_df.head(10)

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np


companies = final_df["Company Name"].tolist()
values = final_df["Absolute Current Price (%)"].tolist()


norm = mcolors.TwoSlopeNorm(vmin=min(values), vcenter=0, vmax=max(values))
cmap = plt.get_cmap("RdYlGn")


n = len(companies)
cols = 7
rows = int(np.ceil(n / cols))

fig, ax = plt.subplots(figsize=(20, 12))

for i, (company, val) in enumerate(zip(companies, values)):
    row = i // cols
    col = i % cols

    color = cmap(norm(val))

    rect = plt.Rectangle((col, rows - row - 1), 1, 1, facecolor=color, edgecolor="black")
    ax.add_patch(rect)


    ax.text(col + 0.5, rows - row - 0.5,
            f"{company}\n{val:.2f}%",
            ha="center", va="center",
            fontsize=9, wrap=True)


ax.set_xlim(0, cols)
ax.set_ylim(0, rows)


ax.axis("off")

# Title
plt.title("Stock Performance Heatmap (Recorded price - current price)", fontsize=18)
plt.tight_layout()
plt.show()

final_df.head(1)

companies = final_df['Company Name'].tolist()
values = final_df['Absolute 3M Price (%)'].tolist()

norm = mcolors.TwoSlopeNorm(vmin = min(values), vcenter = 0, vmax = max(values))
cmap = plt.get_cmap('RdYlGn')

n = len(companies)
cols = 7
rows = int(np.ceil(n / cols))


fig, ax = plt.subplots(figsize = (20,12))

for i, (Company, val) in enumerate(zip(companies, values)):
  row = i // cols
  col = i % cols

  color = cmap(norm(val))

  rect = plt.Rectangle((col, rows - row - 1), 1 , 1, facecolor = color, edgecolor = 'black')
  ax.add_patch(rect)

  ax.text(col + 0.5, rows - row - 0.5,
          f"{Company}\n{val:.2f}%",
          ha = 'center', va = 'center',
          fontsize = 9, wrap = True)

ax.set_xlim(0, cols)
ax.set_ylim(0, rows)

ax.axis('off')

plt.title("Stock performance of last 3 Months")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np


companies = final_df['Company Name'].tolist()
values = final_df['Absolute 6M Price (%)'].tolist()

norm = mcolors.TwoSlopeNorm(vmin= min(values), vcenter= 0, vmax = max(values))
cmap = plt.get_cmap('RdYlGn')

n = len(companies)
cols = 7
rows = int(np.ceil(n/cols))

fig, ax = plt.subplots(figsize = (20,12))

for i, (Company, val) in enumerate(zip(companies, values)):
  row = i // cols
  col = i % cols

  color = cmap(norm(val))

  rect = plt.Rectangle((col, rows - row - 1), 1 , 1, facecolor = color, edgecolor = 'black')
  ax.add_patch(rect)

  ax.text(col + 0.5, rows - row - 0.5,
          f"{Company}\n{val:.2f}%",
          ha = 'center', va = 'center',
          fontsize = 9, wrap = True)

ax.set_xlim(0, cols)
ax.set_ylim(0, rows)

ax.axis('off')

plt.title("Stock performance of last 6 Months")
plt.tight_layout()
plt.show()

final_df

import pandas as pd
import matplotlib.pyplot as plt
import os

# Create a folder to save charts
os.makedirs("charts", exist_ok=True)

for _, row in final_df.iterrows():
    company = row["Company Name"]
    record_price = row["Record Price"]
    current_price = row["Current Price"]
    target_price = row["target Price"]

    # Skip rows with missing company name
    if pd.isna(company):
        continue

    # Collect all prices
    prices = [record_price, current_price, target_price]
    labels = ["Recorded Price", "Current Price", "Target Price"]
    colors = ["red", "black", "green"]

    # Define x positions for dots (just spread them out equally on the line)
    x_positions = [0, 1, 2]

    # Define horizontal line range (min to max price)
    min_price, max_price = min(prices), max(prices)

    # Plot horizontal line
    plt.figure(figsize=(8, 2))
    plt.hlines(y=0, xmin=min_price - 5, xmax=max_price + 5, color="black", linewidth=1)

    # Plot dots on the line
    for price, label, color in zip(prices, labels, colors):
        plt.scatter(price, 0, color=color, s=100, label=label)

    # Add title
    plt.title(company, fontsize=12, weight="bold")

    # Format x-axis
    plt.xticks(fontsize=10)
    plt.yticks([])  # remove y-axis
    plt.legend(loc="upper center", bbox_to_anchor=(0.5, -0.25), ncol=3, fontsize=9, frameon=False)


plt.show()

def top_recommended(df):
    df = df.dropna(subset=["Current Price", "target Price"])
    df["Diff"] = df["target Price"] - df["Current Price"]
    top_5 = df.nlargest(5, "Diff")[["Company Name", "Current Price", "target Price", "Diff"]]
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.bar(top_5["Company Name"], top_5["Diff"], color="green")
    ax.set_title("Top 5 Recommended Stocks (Target - Current Price)")
    ax.set_ylabel("Difference (₹)")
    plt.xticks(rotation=45)
    return fig

top_recommended(final_df)

def top_losers(df):
    df = df.dropna(subset=["Current Price", "Record Price"])
    df["Loss"] = df["Record Price"] - df["Current Price"]
    top_5 = df.nlargest(5, "Loss")[["Company Name", "Current Price", "Record Price", "Loss"]]
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.bar(top_5["Company Name"], top_5["Loss"], color="red")
    ax.set_title("Top 5 Loser Stocks (Recorded - Current Price)")
    ax.set_ylabel("Loss (₹)")
    plt.xticks(rotation=45)
    return fig

top_losers(final_df)


import streamlit as st

final_df.head(1)

import sys

import sys


# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import matplotlib.colors as mcolors
# import numpy as np
# import plotly.express as px  # Added for crisp pie chart
# import yfinance as yf
# from io import BytesIO
# from textblob import TextBlob
# from gnews import GNews
# from datetime import datetime, timedelta
# 
# # -----------------------------
# # Page config
# # -----------------------------
# st.set_page_config(
#     page_title="Stock Analysis Dashboard",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # Custom CSS for enhanced aesthetics
# st.markdown("""
#     <style>
#     .main { padding: 1rem; }
#     .stTabs [data-baseweb="tab-list"] { gap: 10px; }
#     .stTabs [data-baseweb="tab"] {
#         background-color: #f0f2f6;
#         border-radius: 8px;
#         padding: 8px 16px;
#         font-weight: 500;
#         color: #333;
#     }
#     .stTabs [aria-selected="true"] {
#         background-color: #1e88e5;
#         color: white;
#     }
#     .sidebar .sidebar-content { background-color: #f8f9fa; }
#     .stButton>button {
#         background-color: #1e88e5;
#         color: white;
#         border-radius: 8px;
#         border: none;
#         padding: 8px 16px;
#     }
#     .stButton>button:hover { background-color: #1565c0; }
#     .stDataFrame { border: 1px solid #ddd; border-radius: 8px; }
#     h1, h2, h3 { font-family: 'Arial', sans-serif; }
#     .metric-card {
#         background-color: #f0f2f6;
#         padding: 1rem;
#         border-radius: 8px;
#         box-shadow: 0 2px 4px rgba(0,0,0,0.1);
#         margin-bottom: 1rem;
#     }
#     </style>
# """, unsafe_allow_html=True)
# 
# 
# @st.cache_data
# def load_data():
#     df = pd.read_csv("BSE_Final_Output.csv", index_col=False)
# 
# 
#     if "Index" not in df.columns:
#         for col in df.columns:
#             if "index" in col.lower() or "unnamed" in col.lower():
#                 df.rename(columns={col: "Index"}, inplace=True)
#                 break
#         if "Index" not in df.columns:
#             st.warning("Warning: 'Index' column not found in BSE_Final_Output.csv. Please ensure it exists.")
# 
#     df["Date of Publishing"] = pd.to_datetime(df["Date of Publishing"], dayfirst=True, errors="coerce")
#     df = df.dropna(subset=["Record Price", "Current Price", "target Price"])
#     df["Diff"] = df["Current Price"] - df["Record Price"]
#     df["Percent Change"] = (df["Diff"] / df["Record Price"] * 100).round(2)
#     df["Loss"] = -df["Diff"]
#     df["Distance from Target (%)"] = ((df["Current Price"] - df["target Price"]) / df["target Price"] * 100).round(2)
#     return df
# 
# final_df = load_data()
# 
# # -----------------------------
# # Yahoo Ticker Mapping
# # -----------------------------
# company_tickers = {
#     "Anthony Waste Handling Cell Ltd": "AWHCL.BO",
#     "Narayana Hrudayalaya Ltd": "NH.BO",
#     "A.K. Capital Services Ltd": "AKCAPIT.BO",
#     "Ashok Leyland Ltd": "ASHOKLEY.BO",
#     "Signpost India Ltd": "SIGNPOST.BO",
#     "Action Construction Equipment Ltd": "ACE.BO",
#     "Rupa & Company Ltd": "RUPA.BO",
#     "Dollar Industries Ltd": "DOLLAR.BO",
#     "Ather Energy Ltd": "ATHERENERG.BO",
#     "LG Balakrishnan & Bros Ltd": "LGBBROSLTD.BO",
#     "Avenue Supermarts Ltd": "DMART.BO",
#     "Ethos Ltd": "ETHOSLTD.BO",
#     "Redington Ltd": "REDINGTON.BO",
#     "IndiaMART Inter Ltd": "INDIAMART.BO",
#     "GE Shipping Company Ltd": "GESHIP.BO",
#     "EMS Ltd": "EMSLIMITED.BO",
#     "Fedbank Financial Services Ltd": "FEDFINA.BO",
#     "South Indian Bank Ltd": "SOUTHBANK.BO",
#     "IndusInd Bank Ltd": "INDUSINDBK.BO",
#     "Amara Raja Energy & Mobility Ltd": "ARE&M.BO",
#     "Hyundai Motor India Ltd": "HYUNDAI.BO",
#     "PNB Gilts Ltd": "PNBGILTS.BO",
#     "Concord Enviro Systems Ltd": "CEWATER.BO",
#     "BEML Ltd": "BEML.BO",
#     "Mahanagar Gas Ltd": "MGL.BO",
#     "Jio Financial Services Ltd": "JIOFIN.BO",
#     "WPIL Ltd": "WPIL.BO",
#     "Kirloskar Brothers Ltd": "KIRLOSBROS.BO",
#     "Vardhman Textiles Ltd": "VTL.BO",
#     "ICICI Lombard General Insurance Co Ltd": "ICICIGI.BO",
#     "TTK Prestige Ltd": "TTKPRESTIG.BO",
#     "Galaxy Surfactants Ltd": "GALAXYSURF.BO",
#     "Updater Services Ltd": "UDS.BO",
#     "RateGain Travel Technologies Ltd": "RATEGAIN.BO",
#     "IGI Ltd": "IGIL.BO",
#     "Hindalco Industries Ltd": "HINDALCO.BO",
#     "Jindal Saw Ltd": "JINDALSAW.BO",
#     "Hero MotoCorp Ltd": "HEROMOTOCO.BO",
#     "Geojit Financial Services Ltd": "GEOJITFSL.BO",
#     "Indian Energy Exchange Ltd": "IEX.BO",
#     "Tata Consultancy Services Ltd": "TCS.BO",
#     "Eicher Motors Ltd": "EICHERMOT.BO"
# }
# 
# # -----------------------------
# # Theme Toggle
# # -----------------------------
# theme_choice = st.sidebar.radio("Theme", ["Light", "Dark"], index=1)
# 
# if theme_choice == "Dark":
#     bg_color = "#1a1a1a"
#     fg_color = "white"
#     tracker_bg = "#1a1a1a"
#     cmap = plt.get_cmap("RdYlGn")
# else:
#     bg_color = "white"
#     fg_color = "black"
#     tracker_bg = "white"
#     cmap = plt.get_cmap("RdYlGn")
# 
# # -----------------------------
# # Time Period Filtering
# # -----------------------------
# today = pd.to_datetime("today")
# time_period = st.sidebar.selectbox(
#     "Select Time Period",
#     ["Last 3 Months", "Last 6 Months", "Last 1 Year", "All Time"],
#     help="Filter stocks based on when they were published."
# )
# 
# if time_period == "Last 3 Months":
#     start_date = today - timedelta(days=90)
#     filtered_time_df = final_df[final_df["Date of Publishing"] >= start_date]
# elif time_period == "Last 6 Months":
#     start_date = today - timedelta(days=180)
#     filtered_time_df = final_df[final_df["Date of Publishing"] >= start_date]
# elif time_period == "Last 1 Year":
#     start_date = today - timedelta(days=365)
#     filtered_time_df = final_df[final_df["Date of Publishing"] >= start_date]
# else:
#     filtered_time_df = final_df
# 
# # -----------------------------
# # Sidebar - Filters and Downloads
# # -----------------------------
# with st.sidebar:
#     st.markdown("## Stock Analysis Dashboard")
#     selected_companies = st.multiselect(
#         "Search & Select Companies",
#         options=final_df["Company Name"].dropna().unique().tolist(),
#         default=["Jindal Saw Ltd"],
#         help="Select one or more companies to analyze their trends and performance."
#     )
# 
#     heatmap_options = ["Recorded Price - Current Price", "Last 3 Months", "Last 6 Months"]
#     selected_heatmap = st.selectbox("Choose Heatmap", heatmap_options)
# 
#     date_range = st.date_input(
#         "Select Trend Date Range",
#         value=[final_df["Date of Publishing"].min(), pd.to_datetime("today")],
#         help="Choose the date range for stock price trends."
#     )
# 
#     # Download buttons
#     st.markdown("### Download Reports")
#     filtered_df = final_df[final_df["Company Name"].isin(selected_companies)]
#     def convert_df(df, filetype="csv"):
#         if filetype == "csv":
#             return df.to_csv(index=False).encode("utf-8")
#         elif filetype == "excel":
#             output = BytesIO()
#             with pd.ExcelWriter(output, engine="openpyxl") as writer:
#                 df.to_excel(writer, index=False, sheet_name="Report")
#             return output.getvalue()
# 
#     st.download_button("Download CSV (Selected)", convert_df(filtered_df, "csv"), "report.csv")
#     st.download_button("Download Excel (Selected)", convert_df(filtered_df, "excel"), "report.xlsx")
#     st.download_button("Download CSV (Time Filtered)", convert_df(filtered_time_df, "csv"), "time_filtered_report.csv")
#     st.download_button("Download Excel (Time Filtered)", convert_df(filtered_time_df, "excel"), "time_filtered_report.xlsx")
# 
# # -----------------------------
# # Main Content - Tabbed Layout
# # -----------------------------
# tab1, tab2, tab3, tab4 = st.tabs(["Overview", "Stock Trends", "Performance Analysis", "Market Sentiment"])
# 
# with tab1:
#     st.header("Dashboard Overview")
#     st.markdown("Welcome to the Stock Analysis Dashboard! Explore stock performance, trends, and market sentiment.")
# 
#     # Summary Metrics
#     col1, col2, col3 = st.columns(3)
#     with col1:
#         st.markdown('<div class="metric-card">', unsafe_allow_html=True)
#         st.metric("Total Stocks", len(final_df))
#         st.markdown('</div>', unsafe_allow_html=True)
#     with col2:
#         st.markdown('<div class="metric-card">', unsafe_allow_html=True)
#         st.metric("Avg. Performance", f"{final_df['Percent Change'].mean():.2f}%")
#         st.markdown('</div>', unsafe_allow_html=True)
#     with col3:
#         st.markdown('<div class="metric-card">', unsafe_allow_html=True)
#         top_performer = final_df.loc[final_df["Percent Change"].idxmax(), "Company Name"]
#         st.metric("Top Performer", top_performer)
#         st.markdown('</div>', unsafe_allow_html=True)
# 
#     # Pie Chart - Stock Index Distribution (Plotly - crisp & compact)
#     st.markdown("### Index Distribution")
#     if "Index" in final_df.columns:
#         index_counts = final_df["Index"].value_counts().reset_index()
#         index_counts.columns = ["Index", "Count"]
# 
#         # Modern, vibrant colour palette (works in Light & Dark)
#         palette = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b"]
# 
#         fig = px.pie(
#             index_counts,
#             names="Index",
#             values="Count",
#             color_discrete_sequence=palette,
#             hole=0.0,
#             title="Stocks by Index",
#         )
# 
#         fig.update_traces(
#             textinfo="percent+label",
#             textposition="outside",
#             marker=dict(line=dict(color="#fff", width=2)),
#             pull=[0.08 if i == index_counts["Count"].idxmax() else 0 for i in range(len(index_counts))],
#         )
# 
#         fig.update_layout(
#             height=300,
#             width=300,
#             margin=dict(l=20, r=20, t=50, b=20),
#             title=dict(
#                 font=dict(size=14, color=fg_color, family="Arial"),
#                 x=0.5,
#                 xanchor="center",
#             ),
#             legend=dict(
#                 font=dict(size=10, color=fg_color),
#                 orientation="h",
#                 yanchor="bottom",
#                 y=-0.2,
#                 xanchor="center",
#                 x=0.5,
#             ),
#             paper_bgcolor=bg_color,
#             plot_bgcolor=bg_color,
#         )
# 
#         st.plotly_chart(fig, use_container_width=False)
#     else:
#         st.warning("Warning: 'Index' column not found in the data. Please add it to BSE_Final_Output.csv to view the pie chart.")
# 
#     st.subheader("Stocks Published in Selected Period")
#     st.markdown(f"Showing stocks published in {time_period.lower()}.")
#     def style_dataframe(df):
#         def highlight_percent(val):
#             color = 'green' if val > 0 else 'red' if val < 0 else 'black'
#             return f'color: {color}'
#         return df.style.format({
#             "Record Price": "₹{:.2f}",
#             "Current Price": "₹{:.2f}",
#             "target Price": "₹{:.2f}",
#             "Percent Change": "{:.2f}%",
#             "Distance from Target (%)": "{:.2f}%"
#         }, na_rep="N/A").applymap(highlight_percent, subset=["Percent Change", "Distance from Target (%)"])
# 
#     st.dataframe(
#         style_dataframe(filtered_time_df[[
#             "Company Name", "Ticker", "Date of Publishing",
#             "Record Price", "Current Price", "target Price",
#             "Percent Change", "Distance from Target (%)"
#         ]]),
#         use_container_width=True,
#         column_config={
#             "Company Name": st.column_config.TextColumn("Company", width="large"),
#             "Ticker": st.column_config.TextColumn("Ticker", width="medium"),
#             "Date of Publishing": st.column_config.DateColumn("Published", width="medium"),
#             "Record Price": st.column_config.NumberColumn("Record Price (₹)", width="medium"),
#             "Current Price": st.column_config.NumberColumn("Current Price (₹)", width="medium"),
#             "target Price": st.column_config.NumberColumn("Target Price (₹)", width="medium"),
#             "Percent Change": st.column_config.NumberColumn("Change (%)", width="medium"),
#             "Distance from Target (%)": st.column_config.NumberColumn("To Target (%)", width="medium")
#         }
#     )
# 
# with tab2:
#     st.header("Stock Trends")
#     st.markdown("Analyze price trends and trackers for selected companies.")
#     for selected_company in selected_companies:
#         with st.container():
#             st.subheader(f"{selected_company}")
#             if selected_company in company_tickers:
#                 ticker = company_tickers[selected_company]
#                 with st.spinner(f"Fetching data for {selected_company}..."):
#                     data = yf.download(ticker, start=pd.to_datetime(date_range[0]), end=pd.to_datetime(date_range[1]))
#                 if not data.empty:
#                     data.reset_index(inplace=True)
#                     target_price = final_df.loc[final_df["Company Name"] == selected_company, "target Price"].values[0]
#                     first_close, last_close = float(data['Close'].iloc[0]), float(data['Close'].iloc[-1])
#                     trend_color = 'green' if last_close > first_close else 'red'
# 
#                     # Trend Line
#                     fig_trend, ax_trend = plt.subplots(figsize=(10, 4))
#                     ax_trend.plot(data["Date"], data["Close"], label="Close Price", color=trend_color, linewidth=2)
#                     ax_trend.axhline(y=target_price, color="orange", linestyle="--", label=f"Target {target_price:.0f}")
#                     ax_trend.set_title(f"{selected_company} Trend", fontsize=12, color=fg_color, pad=12)
#                     ax_trend.tick_params(colors=fg_color)
#                     ax_trend.grid(True, alpha=0.3)
#                     fig_trend.patch.set_facecolor(bg_color)
#                     ax_trend.set_facecolor(bg_color)
#                     ax_trend.legend(facecolor=bg_color, edgecolor=fg_color, labelcolor=fg_color)
#                     st.pyplot(fig_trend)
# 
#                     # Horizontal Price Tracker
#                     selected_row = final_df[final_df["Company Name"] == selected_company].iloc[0]
#                     prices = [selected_row["Record Price"], selected_row["Current Price"], selected_row["target Price"]]
#                     labels = ["Recorded", "Current", "Target"]
#                     colors = ["red", "white", "green"]
# 
#                     min_price, max_price = min([p for p in prices if pd.notna(p)]), max([p for p in prices if pd.notna(p)])
#                     fig4, ax4 = plt.subplots(figsize=(8, 2))
#                     fig4.patch.set_facecolor(tracker_bg)
#                     ax4.set_facecolor(tracker_bg)
#                     ax4.hlines(y=0, xmin=min_price - 5, xmax=max_price + 5, color=fg_color, linewidth=1)
# 
#                     for price, label, color in zip(prices, labels, colors):
#                         if pd.notna(price):
#                             ax4.scatter(price, 0, color=color, s=50)
#                             ax4.annotate(
#                                 f"{label}\n₹{price:.2f}",
#                                 (price, 0),
#                                 xytext=(0, 15),
#                                 textcoords="offset points",
#                                 ha="center", va="bottom",
#                                 fontsize=8, color=color, weight="bold"
#                             )
# 
#                     ax4.set_xticks([])
#                     ax4.set_yticks([])
#                     ax4.set_title(f"{selected_company} Price Tracker", fontsize=10, color=fg_color, pad=2)
#                     plt.tight_layout(pad=0.5)
#                     st.pyplot(fig4)
# 
#                     # Dynamic Alert
#                     current_price = selected_row["Current Price"]
#                     if pd.notna(current_price) and abs((current_price - target_price) / target_price) <= 0.05:
#                         st.success(f"{selected_company} is within ±5% of Target Price!")
#                 else:
#                     st.warning("Warning: No Yahoo Finance data found for this stock.")
#             else:
#                 st.info("Info: Ticker not mapped yet for this company.")
# 
# with tab3:
#     st.header("Performance Analysis")
#     st.markdown("Visualize stock performance over time and top performers.")
# 
#     # Bar Chart for Percentage Change
#     with st.container():
#         st.subheader(f"Performance Chart ({time_period})")
#         chart_data = filtered_time_df[["Company Name", "Percent Change"]].dropna()
#         if not chart_data.empty:
#             fig, ax = plt.subplots(figsize=(10, 6))
#             companies = chart_data["Company Name"].tolist()
#             percent_changes = chart_data["Percent Change"].tolist()
#             colors = ['#00cc44' if x > 0 else '#ff3333' for x in percent_changes]
# 
#             bars = ax.bar(companies, percent_changes, color=colors, edgecolor=['#009933' if x > 0 else '#cc0000' for x in percent_changes])
#             ax.set_title(f"Stock Performance ({time_period})", fontsize=12, color=fg_color)
#             ax.set_ylabel("Percent Change (%)", fontsize=10, color=fg_color)
#             ax.tick_params(axis='x', rotation=45, colors=fg_color)
#             ax.tick_params(axis='y', colors=fg_color)
#             ax.grid(True, alpha=0.3)
#             fig.patch.set_facecolor(bg_color)
#             ax.set_facecolor(bg_color)
#             for bar in bars:
#                 height = bar.get_height()
#                 ax.text(bar.get_x() + bar.get_width()/2., height, f'{height:.2f}%',
#                         ha='center', va='bottom' if height >= 0 else 'top', fontsize=8, color=fg_color)
#             plt.tight_layout()
#             st.pyplot(fig)
#         else:
#             st.warning("No valid data available for the chart.")
# 
#     # Heatmap
#     with st.container():
#         st.subheader("Stock Performance Heatmap")
#         companies = final_df["Company Name"].tolist()
#         if selected_heatmap == "Recorded Price - Current Price":
#             values = final_df["Percent Change"].tolist()
#             title = "Stock Performance (Recorded - Current Price)"
#         elif selected_heatmap == "Last 3 Months":
#             values = final_df["Absolute 3M Price (%)"].tolist()
#             title = "Stock Performance (Last 3 Months)"
#         else:
#             values = final_df["Absolute 6M Price (%)"].tolist()
#             title = "Stock Performance (Last 6 Months)"
# 
#         norm = mcolors.TwoSlopeNorm(vmin=min([v for v in values if pd.notna(v)], default=0),
#                                    vcenter=0,
#                                    vmax=max([v for v in values if pd.notna(v)], default=0))
#         cmap = plt.get_cmap("RdYlGn")
#         cols = 5
#         rows = int(np.ceil(len(companies) / cols))
#         fig1, ax1 = plt.subplots(figsize=(12, max(6, rows * 1.5)))
#         fig1.patch.set_facecolor(bg_color)
#         ax1.set_facecolor(bg_color)
#         for i, (company, val) in enumerate(zip(companies, values)):
#             row, col = divmod(i, cols)
#             color = cmap(norm(val)) if pd.notna(val) else "grey"
#             rect = plt.Rectangle((col, rows - row - 1), 1, 1, facecolor=color, edgecolor=fg_color)
#             ax1.add_patch(rect)
#             ax1.text(col + 0.5, rows - row - 0.5,
#                      f"{company}\n{val:.2f}%" if pd.notna(val) else f"{company}\nN/A",
#                      ha="center", va="center", fontsize=8, color='black', wrap=True)
#         ax1.set_xlim(0, cols)
#         ax1.set_ylim(0, rows)
#         ax1.axis("off")
#         plt.title(title, fontsize=12, color=fg_color)
#         st.pyplot(fig1)
# 
#     # Top Performers
#     with st.container():
#         st.subheader("Top Performers")
#         col3, col4 = st.columns(2)
#         with col3:
#             st.markdown("### Top 5 Gainers")
#             gainers_df = final_df[final_df["Diff"] > 0].nlargest(5, "Diff")
#             if not gainers_df.empty:
#                 st.dataframe(
#                     gainers_df[["Company Name", "Current Price", "Record Price", "Diff", "Percent Change"]].style.format({
#                         "Current Price": "₹{:.2f}",
#                         "Record Price": "₹{:.2f}",
#                         "Diff": "₹{:.2f}",
#                         "Percent Change": "{:.2f}%"
#                     }, na_rep="N/A"),
#                     use_container_width=True
#                 )
#             else:
#                 st.info("No gainers available.")
#         with col4:
#             st.markdown("### Top 5 Losers")
#             losers_df = final_df[final_df["Diff"] < 0].nlargest(5, "Loss")
#             if not losers_df.empty:
#                 st.dataframe(
#                     losers_df[["Company Name", "Current Price", "Record Price", "Loss", "Percent Change"]].style.format({
#                         "Current Price": "₹{:.2f}",
#                         "Record Price": "₹{:.2f}",
#                         "Loss": "₹{:.2f}",
#                         "Percent Change": "{:.2f}%"
#                     }, na_rep="N/A"),
#                     use_container_width=True
#                 )
#             else:
#                 st.info("No losers available.")
# 
# with tab4:
#     st.header("Market Sentiment")
#     st.markdown("Analyze recent news sentiment for the Indian stock market.")
#     headlines = []
#     try:
#         google_news = GNews(language='en', country='IN', max_results=5)
#         google_headlines = google_news.get_news("Indian stock market")
#         for item in google_headlines:
#             headlines.append(item['title'])
#     except:
#         st.warning("Warning: Could not fetch Google News.")
# 
#     if headlines:
#         sentiment_data = []
#         for headline in headlines:
#             sentiment = TextBlob(headline).sentiment.polarity
#             if sentiment > 0.1:
#                 sentiment_label = "Positive"
#             elif sentiment < -0.1:
#                 sentiment_label = "Negative"
#             else:
#                 sentiment_label = "Neutral"
#             sentiment_data.append(sentiment)
#             st.markdown(f"- {headline} → **{sentiment_label}**")
# 
#         avg_sentiment = np.mean(sentiment_data)
#         if avg_sentiment > 0.1:
#             st.success(f"Overall Market Sentiment: Positive ({avg_sentiment:.2f})")
#         elif avg_sentiment < -0.1:
#             st.error(f"Overall Market Sentiment: Negative ({avg_sentiment:.2f})")
#         else:
#             st.info(f"Overall Market Sentiment: Neutral ({avg_sentiment:.2f})")
#     else:
#         st.info("No news available for sentiment analysis.")

!streamlit run app.py

"""I've added a new cell with the corrected command to run your Streamlit app.

I've added a cell to install `streamlit`. Once that's done, you should be able to run the Streamlit app code without the `ModuleNotFoundError`.

The error `ModuleNotFoundError: No module named 'streamlit'` means that when the code in cell `klcAEbLERY5Z` was executed, the Python interpreter could not find the `streamlit` library. This happens when a library is used without being installed first. The `!pip install streamlit` command in the new cell will download and install the library, making it available for use in your notebook.
"""

